"use client";

import React from "react";
import { Table, Row, Col, Button } from "react-bootstrap";
import { FaTimesCircle } from "react-icons/fa";
import { productsIngredientsDataFormatter } from "@/utils/data_formatters/productsPageDataFormatter";
import { useProductIngredients } from "@/services/product-service";
import ServiceRenderer from "@/components/common/ServiceRenderer/ServiceRenderer";
import { useProductsContext } from "@/contexts/ProductsContext";

const ProductsIngredients = () => {
  const { startDate, endDate } = useProductsContext();

  return (
    <ServiceRenderer
      queryHook={useProductIngredients}
      queryKey={["productIngredients", { startdt: startDate, enddt: endDate }]}
      queryFn={() =>
        useProductIngredients({ startdt: startDate, enddt: endDate }).queryFn
      }
      queryArgs={[100,{ startdt: startDate, enddt: endDate }]}
      shimmerCount={1}
    >
      {(apiData) => {
        const { product, list } = apiData;

        return (
          <div className="p-3 bg-white rounded shadow-sm">
            {/* Header Summary */}
            <Row className="mb-3">
              <Col className="border rounded py-2 text-center">
                <div className="text-muted small">Total Items</div>
                <div className="fw-bold fs-5">{list?.length || 0}</div>
              </Col>
              <Col className="border rounded py-2 text-center">
                <div className="text-muted small">Total Cost</div>
                <div className="fw-bold fs-5 text-success">
                  ₹
                  {list
                    ?.reduce((acc, curr) => acc + curr.ingredientPrice, 0)
                    .toFixed(2)}
                </div>
              </Col>
              <Col xs="auto" className="d-flex align-items-center">
                <Button variant="light" className="p-2 rounded-circle shadow-sm">
                  <FaTimesCircle size={20} className="text-secondary" />
                </Button>
              </Col>
            </Row>

            {/* Table */}
            <Table bordered hover responsive className="align-middle">
              <thead className="bg-primary text-white">
                <tr>
                  <th>Item</th>
                  <th>Ingredient</th>
                  <th>Item Price</th>
                  <th>Quantity</th>
                  <th>Total Price</th>
                </tr>
              </thead>
              <tbody>
                {list && list.length > 0 ? (
                  list.map((ingredient, idx) => {
                    const row = productsIngredientsDataFormatter(ingredient);
                    return (
                      <tr key={idx}>
                        <td>{row.itemType}</td>
                        <td>{row.ingredient}</td>
                        <td>{row.itemPrice}</td>
                        <td>{row.quantity}</td>
                        <td>{row.totalPrice}</td>
                      </tr>
                    );
                  })
                ) : (
                  <tr>
                    <td colSpan="5" className="text-center text-muted py-3">
                      No Ingredients Available
                    </td>
                  </tr>
                )}
              </tbody>
            </Table>
          </div>
        );
      }}
    </ServiceRenderer>
  );
};

export default ProductsIngredients;

// import React from "react";
// import { Table, Row, Col, Button } from "react-bootstrap";
// import { FaTimesCircle } from "react-icons/fa";
// import { productsIngredientsDataFormatter } from "@/utils/data_formatters/productsPageDataFormatter";

// const ProductsIngredients = ({
//   data = {
//     etag: "328926118",
//     productId: "100",
//     product: {
//       id: "100",
//       outletId: "1",
//       name: "Butter Chicken (Half)",
//       departmentId: 2,
//       departmentName: "NORTH INDIAN",
//       masterProductId: 93,
//       masterProductName: "Butter Chicken",
//       categoryId: 0,
//       categoryName: null,
//       price: 279,
//       makingCost: 106,
//       costPercentage: 37.99,
//       marginPercentage: 62.01,
//       veg: false,
//       imageUrl: null,
//       preparationTime: 0,
//       variation: "FULL",
//       displayOrder: 0,
//       description: null,
//       pieceCount: 1,
//       pieceQuantity: 1,
//       pieceUnit: "GM",
//       disabled: false,
//       createdTs: null,
//       updatedTs: null,
//       createdBy: null,
//       updatedBy: null,
//     },
//     totalIngredientCount: 0,
//     totalIngredientCost: 0,
//     totalUsageCost: 0,
//     list: [
//       {
//         itemId: "20",
//         item: {
//           id: "20",
//           outletId: "1",
//           name: "CHICKEN THIGH BONELESS",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 315,
//           categoryId: 1,
//           categoryName: "Chicken",
//           disabled: false,
//           alias: "CHICKEN THIGH BONELESS - 1000GM",
//           moq: 13800,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 315,
//         ingredientQuantity: 120,
//         ingredientPrice: 37.8,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "28",
//         item: {
//           id: "28",
//           outletId: "1",
//           name: "RICH CREAM FRESH",
//           unit: "ML",
//           unitQuantity: "1000",
//           unitPrice: 208.3,
//           categoryId: 4,
//           categoryName: "Dairy",
//           disabled: false,
//           alias: "RICH CREAM FRESH - 1000ML",
//           moq: 1267,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 215,
//         ingredientQuantity: 35,
//         ingredientPrice: 7.525,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "31",
//         item: {
//           id: "31",
//           outletId: "1",
//           name: "AMUL BUTTER",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 267.4,
//           categoryId: 4,
//           categoryName: "Dairy",
//           disabled: false,
//           alias: "AMUL BUTTER - 500GM",
//           moq: 1373,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 290,
//         ingredientQuantity: 20,
//         ingredientPrice: 11.6,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "74",
//         item: {
//           id: "74",
//           outletId: "1",
//           name: "GOLD DROP OIL",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 115.7,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "GOLD DROP OIL - 1000GM",
//           moq: 25840,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 157.4,
//         ingredientQuantity: 20,
//         ingredientPrice: 3.148,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "79",
//         item: {
//           id: "79",
//           outletId: "1",
//           name: "TATA SALT",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 24,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "TATA SALT - 1000GM",
//           moq: 5533,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 24,
//         ingredientQuantity: 15,
//         ingredientPrice: 0.36,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "27",
//         item: {
//           id: "27",
//           outletId: "1",
//           name: "GHEE",
//           unit: "ML",
//           unitQuantity: "1000",
//           unitPrice: 580,
//           categoryId: 4,
//           categoryName: "Dairy",
//           disabled: false,
//           alias: "GHEE - 1000ML",
//           moq: 1750,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 560,
//         ingredientQuantity: 8,
//         ingredientPrice: 4.48,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "101",
//         item: {
//           id: "101",
//           outletId: "1",
//           name: "KASHMIRI CHILLI POWDER( MDH)",
//           unit: "GM",
//           unitQuantity: "100",
//           unitPrice: 115,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "KASHMIRI CHILLI POWDER( MDH) - 100GM",
//           moq: 327,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 100,
//         unitPrice: 88,
//         ingredientQuantity: 8,
//         ingredientPrice: 7.04,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "77",
//         item: {
//           id: "77",
//           outletId: "1",
//           name: "SWASTIK CHILLI POWDER",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 137,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SWASTIK CHILLI POWDER - 500GM",
//           moq: 2467,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 115,
//         ingredientQuantity: 5,
//         ingredientPrice: 1.15,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "87",
//         item: {
//           id: "87",
//           outletId: "1",
//           name: "JEERA",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 390,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "JEERA - 1000GM",
//           moq: 330,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 265,
//         ingredientQuantity: 5,
//         ingredientPrice: 1.325,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "109",
//         item: {
//           id: "109",
//           outletId: "1",
//           name: "WHOLE CORIANDER SEEDS",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 130,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "WHOLE CORIANDER SEEDS - 1000GM",
//           moq: 517,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 130,
//         ingredientQuantity: 5,
//         ingredientPrice: 0.65,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "179",
//         item: {
//           id: "179",
//           outletId: "1",
//           name: "GINGER",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 160,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "GINGER - 1000GM",
//           moq: 1130,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 80,
//         ingredientQuantity: 5,
//         ingredientPrice: 0.4,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "180",
//         item: {
//           id: "180",
//           outletId: "1",
//           name: "CAPSICUM",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 45,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "CAPSICUM - 1000GM",
//           moq: 0,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 60,
//         ingredientQuantity: 5,
//         ingredientPrice: 0.3,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "182",
//         item: {
//           id: "182",
//           outletId: "1",
//           name: "WHOLE GARLIC",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 200,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "WHOLE GARLIC - 1000GM",
//           moq: 3427,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 95,
//         ingredientQuantity: 5,
//         ingredientPrice: 0.475,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "75",
//         item: {
//           id: "75",
//           outletId: "1",
//           name: "HALDI",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 127,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "HALDI - 500GM",
//           moq: 733,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 135,
//         ingredientQuantity: 4,
//         ingredientPrice: 1.08,
//         baseItemId: null,
//         baseItem: null,
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "176",
//         item: {
//           id: "176",
//           outletId: "1",
//           name: "ONION",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 40,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "ONION - 1000GM",
//           moq: 52947,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 26,
//         ingredientQuantity: 850,
//         ingredientPrice: 22.1,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "80",
//         item: {
//           id: "80",
//           outletId: "1",
//           name: "TOMATO",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 35,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "TOMATO - 1000GM",
//           moq: 30260,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 33,
//         ingredientQuantity: 670,
//         ingredientPrice: 22.11,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "74",
//         item: {
//           id: "74",
//           outletId: "1",
//           name: "GOLD DROP OIL",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 115.7,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "GOLD DROP OIL - 1000GM",
//           moq: 25840,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 157.4,
//         ingredientQuantity: 170,
//         ingredientPrice: 26.758,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "473",
//         item: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 78,
//         ingredientQuantity: 30,
//         ingredientPrice: 2.34,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "179",
//         item: {
//           id: "179",
//           outletId: "1",
//           name: "GINGER",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 160,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "GINGER - 1000GM",
//           moq: 1130,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 80,
//         ingredientQuantity: 20,
//         ingredientPrice: 1.6,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "182",
//         item: {
//           id: "182",
//           outletId: "1",
//           name: "WHOLE GARLIC",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 200,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "WHOLE GARLIC - 1000GM",
//           moq: 3427,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 95,
//         ingredientQuantity: 20,
//         ingredientPrice: 1.9,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "77",
//         item: {
//           id: "77",
//           outletId: "1",
//           name: "SWASTIK CHILLI POWDER",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 137,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SWASTIK CHILLI POWDER - 500GM",
//           moq: 2467,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 115,
//         ingredientQuantity: 8,
//         ingredientPrice: 1.84,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "87",
//         item: {
//           id: "87",
//           outletId: "1",
//           name: "JEERA",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 390,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "JEERA - 1000GM",
//           moq: 330,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 265,
//         ingredientQuantity: 8,
//         ingredientPrice: 2.12,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "75",
//         item: {
//           id: "75",
//           outletId: "1",
//           name: "HALDI",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 127,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "HALDI - 500GM",
//           moq: 733,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 135,
//         ingredientQuantity: 3,
//         ingredientPrice: 0.81,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "100",
//         item: {
//           id: "100",
//           outletId: "1",
//           name: "GREEN CARDAMOM",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 2100,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "GREEN CARDAMOM - 1000GM",
//           moq: 147,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 2900,
//         ingredientQuantity: 3,
//         ingredientPrice: 8.7,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "106",
//         item: {
//           id: "106",
//           outletId: "1",
//           name: "SHAHI JEERA",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 850,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SHAHI JEERA - 1000GM",
//           moq: 179,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 980,
//         ingredientQuantity: 3,
//         ingredientPrice: 2.94,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "116",
//         item: {
//           id: "116",
//           outletId: "1",
//           name: "CINNAMON",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 380,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "CINNAMON - 1000GM",
//           moq: 186,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 270,
//         ingredientQuantity: 3,
//         ingredientPrice: 0.81,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "199",
//         item: {
//           id: "199",
//           outletId: "1",
//           name: "CLOVE",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 1150,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "CLOVE - 1000GM",
//           moq: 42,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 880,
//         ingredientQuantity: 2,
//         ingredientPrice: 1.76,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "115",
//         item: {
//           id: "115",
//           outletId: "1",
//           name: "BAY LEAF",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 90,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "BAY LEAF - 1000GM",
//           moq: 1,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 90,
//         ingredientQuantity: 1,
//         ingredientPrice: 0.09,
//         baseItemId: "473",
//         baseItem: {
//           id: "473",
//           outletId: "1",
//           name: "Chow Masala",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 78,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Chow Masala - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "80",
//         item: {
//           id: "80",
//           outletId: "1",
//           name: "TOMATO",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 35,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "TOMATO - 1000GM",
//           moq: 30260,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 33,
//         ingredientQuantity: 660,
//         ingredientPrice: 21.78,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "474",
//         item: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 116.2,
//         ingredientQuantity: 200,
//         ingredientPrice: 23.24,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "83",
//         item: {
//           id: "83",
//           outletId: "1",
//           name: "CASHEW NUTS 1/8",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 650,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "CASHEW NUTS 1/8 - 1000GM",
//           moq: 3317,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 390,
//         ingredientQuantity: 67,
//         ingredientPrice: 26.13,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "85",
//         item: {
//           id: "85",
//           outletId: "1",
//           name: "MELON SEEDS ( CHAR MAGAZ )",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 700,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "MELON SEEDS ( CHAR MAGAZ ) - 1000GM",
//           moq: 767,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 683,
//         ingredientQuantity: 23,
//         ingredientPrice: 15.709,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "182",
//         item: {
//           id: "182",
//           outletId: "1",
//           name: "WHOLE GARLIC",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 200,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "WHOLE GARLIC - 1000GM",
//           moq: 3427,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 95,
//         ingredientQuantity: 5,
//         ingredientPrice: 0.475,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "179",
//         item: {
//           id: "179",
//           outletId: "1",
//           name: "GINGER",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 160,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "GINGER - 1000GM",
//           moq: 1130,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 80,
//         ingredientQuantity: 5,
//         ingredientPrice: 0.4,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "101",
//         item: {
//           id: "101",
//           outletId: "1",
//           name: "KASHMIRI CHILLI POWDER( MDH)",
//           unit: "GM",
//           unitQuantity: "100",
//           unitPrice: 115,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "KASHMIRI CHILLI POWDER( MDH) - 100GM",
//           moq: 327,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 100,
//         unitPrice: 88,
//         ingredientQuantity: 4,
//         ingredientPrice: 3.52,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "79",
//         item: {
//           id: "79",
//           outletId: "1",
//           name: "TATA SALT",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 24,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "TATA SALT - 1000GM",
//           moq: 5533,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 24,
//         ingredientQuantity: 4,
//         ingredientPrice: 0.096,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "98",
//         item: {
//           id: "98",
//           outletId: "1",
//           name: "SUGAR",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 43,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SUGAR - 1000GM",
//           moq: 2427,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 45,
//         ingredientQuantity: 4,
//         ingredientPrice: 0.18,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "77",
//         item: {
//           id: "77",
//           outletId: "1",
//           name: "SWASTIK CHILLI POWDER",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 137,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SWASTIK CHILLI POWDER - 500GM",
//           moq: 2467,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 115,
//         ingredientQuantity: 4,
//         ingredientPrice: 0.92,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "75",
//         item: {
//           id: "75",
//           outletId: "1",
//           name: "HALDI",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 127,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "HALDI - 500GM",
//           moq: 733,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 135,
//         ingredientQuantity: 2,
//         ingredientPrice: 0.54,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "100",
//         item: {
//           id: "100",
//           outletId: "1",
//           name: "GREEN CARDAMOM",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 2100,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "GREEN CARDAMOM - 1000GM",
//           moq: 147,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 2900,
//         ingredientQuantity: 1,
//         ingredientPrice: 2.9,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "106",
//         item: {
//           id: "106",
//           outletId: "1",
//           name: "SHAHI JEERA",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 850,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SHAHI JEERA - 1000GM",
//           moq: 179,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 980,
//         ingredientQuantity: 1,
//         ingredientPrice: 0.98,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "116",
//         item: {
//           id: "116",
//           outletId: "1",
//           name: "CINNAMON",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 380,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "CINNAMON - 1000GM",
//           moq: 186,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 270,
//         ingredientQuantity: 1,
//         ingredientPrice: 0.27,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "199",
//         item: {
//           id: "199",
//           outletId: "1",
//           name: "CLOVE",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 1150,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "CLOVE - 1000GM",
//           moq: 42,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 880,
//         ingredientQuantity: 1,
//         ingredientPrice: 0.88,
//         baseItemId: "474",
//         baseItem: {
//           id: "474",
//           outletId: "1",
//           name: "Red/Makhani Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 70,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Red/Makhani Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "176",
//         item: {
//           id: "176",
//           outletId: "1",
//           name: "ONION",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 40,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "ONION - 1000GM",
//           moq: 52947,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 26,
//         ingredientQuantity: 550,
//         ingredientPrice: 14.3,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "83",
//         item: {
//           id: "83",
//           outletId: "1",
//           name: "CASHEW NUTS 1/8",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 650,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "CASHEW NUTS 1/8 - 1000GM",
//           moq: 3317,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 390,
//         ingredientQuantity: 112,
//         ingredientPrice: 43.68,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "74",
//         item: {
//           id: "74",
//           outletId: "1",
//           name: "GOLD DROP OIL",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 115.7,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "GOLD DROP OIL - 1000GM",
//           moq: 25840,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 157.4,
//         ingredientQuantity: 75,
//         ingredientPrice: 11.805,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "80",
//         item: {
//           id: "80",
//           outletId: "1",
//           name: "TOMATO",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 35,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "TOMATO - 1000GM",
//           moq: 30260,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 33,
//         ingredientQuantity: 75,
//         ingredientPrice: 2.475,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "85",
//         item: {
//           id: "85",
//           outletId: "1",
//           name: "MELON SEEDS ( CHAR MAGAZ )",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 700,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "MELON SEEDS ( CHAR MAGAZ ) - 1000GM",
//           moq: 767,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 683,
//         ingredientQuantity: 37,
//         ingredientPrice: 25.271,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "480",
//         item: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 109.5,
//         ingredientQuantity: 30,
//         ingredientPrice: 3.285,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "77",
//         item: {
//           id: "77",
//           outletId: "1",
//           name: "SWASTIK CHILLI POWDER",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 137,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "SWASTIK CHILLI POWDER - 500GM",
//           moq: 2467,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 115,
//         ingredientQuantity: 18.5,
//         ingredientPrice: 4.255,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "75",
//         item: {
//           id: "75",
//           outletId: "1",
//           name: "HALDI",
//           unit: "GM",
//           unitQuantity: "500",
//           unitPrice: 127,
//           categoryId: 7,
//           categoryName: "Indian Grocery",
//           disabled: false,
//           alias: "HALDI - 500GM",
//           moq: 733,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 500,
//         unitPrice: 135,
//         ingredientQuantity: 18.5,
//         ingredientPrice: 4.995,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "179",
//         item: {
//           id: "179",
//           outletId: "1",
//           name: "GINGER",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 160,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "GINGER - 1000GM",
//           moq: 1130,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 80,
//         ingredientQuantity: 7.5,
//         ingredientPrice: 0.6,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//       {
//         itemId: "182",
//         item: {
//           id: "182",
//           outletId: "1",
//           name: "WHOLE GARLIC",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 200,
//           categoryId: 5,
//           categoryName: "Vegetables",
//           disabled: false,
//           alias: "WHOLE GARLIC - 1000GM",
//           moq: 3427,
//           itemTypeId: 1,
//           itemType: "Store Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         unitQuantity: 1000,
//         unitPrice: 95,
//         ingredientQuantity: 7.5,
//         ingredientPrice: 0.7125,
//         baseItemId: "480",
//         baseItem: {
//           id: "480",
//           outletId: "1",
//           name: "Yellow/Kaju Gravy",
//           unit: "GM",
//           unitQuantity: "1000",
//           unitPrice: 104,
//           categoryId: 18,
//           categoryName: "Base Items",
//           disabled: false,
//           alias: "Yellow/Kaju Gravy - 1000GM",
//           moq: 5000,
//           itemTypeId: 2,
//           itemType: "Base Item",
//           itemDescription: null,
//           perishable: false,
//           shelfLifeDays: 0,
//           hsnCode: null,
//           brandName: null,
//           storageLocation: null,
//           createdBy: null,
//           updatedBy: null,
//         },
//         totalQuantity: 0,
//         totalPrice: 0,
//       },
//     ],
//   },
// }) => {
//   const { product, list } = data;

//   return (
//     <div className="p-3 bg-white rounded shadow-sm">
//       {/* Header Summary */}
//       <Row className="mb-3">
//         <Col className="border rounded py-2 text-center">
//           <div className="text-muted small">Total Items</div>
//           <div className="fw-bold fs-5">{list?.length || 0}</div>
//         </Col>
//         <Col className="border rounded py-2 text-center">
//           <div className="text-muted small">Total Cost</div>
//           <div className="fw-bold fs-5 text-success">
//             ₹
//             {list
//               ?.reduce((acc, curr) => acc + curr.ingredientPrice, 0)
//               .toFixed(2)}
//           </div>
//         </Col>
//         <Col xs="auto" className="d-flex align-items-center">
//           <Button variant="light" className="p-2 rounded-circle shadow-sm">
//             <FaTimesCircle size={20} className="text-secondary" />
//           </Button>
//         </Col>
//       </Row>

//       {/* Table */}
//       <Table bordered hover responsive className="align-middle">
//         <thead className="bg-primary text-white">
//           <tr>
//             <th>Item</th>
//             <th>Ingredient</th>
//             <th>Item Price</th>
//             <th>Quantity</th>
//             <th>Total Price</th>
//           </tr>
//         </thead>
//         <tbody>
//           {list && list.length > 0 ? (
//             list.map((ingredient, idx) => {
//               const row = productsIngredientsDataFormatter(ingredient);
//               return (
//                 <tr key={idx}>
//                   <td>{row.itemType}</td>
//                   <td>{row.ingredient}</td>
//                   <td>{row.itemPrice}</td>
//                   <td>{row.quantity}</td>
//                   <td>{row.totalPrice}</td>
//                 </tr>
//               );
//             })
//           ) : (
//             <tr>
//               <td colSpan="5" className="text-center text-muted py-3">
//                 No Ingredients Available
//               </td>
//             </tr>
//           )}
//         </tbody>
//       </Table>
//     </div>
//   );
// };

// export default ProductsIngredients;
